/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ReembolsosRouteImport } from './routes/reembolsos'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as RTokenRouteImport } from './routes/r.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsosRoute = ReembolsosRouteImport.update({
  id: '/reembolsos',
  path: '/reembolsos',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/privacidad': typeof PrivacidadRoute
  '/reembolsos': typeof ReembolsosRoute
  '/terminos': typeof TerminosRoute
  '/r/$token': typeof RTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/privacidad': typeof PrivacidadRoute
  '/reembolsos': typeof ReembolsosRoute
  '/terminos': typeof TerminosRoute
  '/r/$token': typeof RTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/privacidad': typeof PrivacidadRoute
  '/reembolsos': typeof ReembolsosRoute
  '/terminos': typeof TerminosRoute
  '/r/$token': typeof RTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/privacidad'
    | '/reembolsos'
    | '/terminos'
    | '/r/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/privacidad'
    | '/reembolsos'
    | '/terminos'
    | '/r/$token'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/privacidad'
    | '/reembolsos'
    | '/terminos'
    | '/r/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ReembolsosRoute: typeof ReembolsosRoute
  TerminosRoute: typeof TerminosRoute
  RTokenRoute: typeof RTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolsos': {
      id: '/reembolsos'
      path: '/reembolsos'
      fullPath: '/reembolsos'
      preLoaderRoute: typeof ReembolsosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  PrivacidadRoute: PrivacidadRoute,
  ReembolsosRoute: ReembolsosRoute,
  TerminosRoute: TerminosRoute,
  RTokenRoute: RTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
